INSERT INTO PRODUCT (CATEGORY, PRICE, NAME) VALUES ('Categoria 1' , 100.00, 'Produto 1' )
INSERT INTO PRODUCT (CATEGORY, PRICE, NAME) VALUES ('Categoria 2' , 200.00, 'Produto 2' )
INSERT INTO PRODUCT (CATEGORY, PRICE, NAME) VALUES ('Categoria 3' , 300.00, 'Produto 3' )